%YAML:1.0

#common parameters
stereo: 1
imu_topic: "/camera/imu"
image_topic_0: "/camera/infra1/image_rect_raw"
image_topic_1: "/camera/infra2/image_rect_raw"
output_dir: "~/tmp/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"

gnss_enable: 1
gnss_meas_topic: "/ublox_driver/range_meas"           # GNSS raw measurement topic
gnss_ephem_topic: "/ublox_driver/ephem"               # GPS, Galileo, BeiDou ephemeris
gnss_glo_ephem_topic: "/ublox_driver/glo_ephem"       # GLONASS ephemeris
gnss_iono_params_topic: "/ublox_driver/iono_params"   # GNSS broadcast ionospheric parameters
gnss_tp_info_topic: "/ublox_driver/time_pulse_info"   # PPS time info
gnss_elevation_thres: 30            # satellite elevation threshold (degree)
gnss_psr_std_thres: 2.0             # pseudo-range std threshold
gnss_dopp_std_thres: 2.0            # doppler std threshold
gnss_track_num_thres: 20            # number of satellite tracking epochs before entering estimator
gnss_ddt_sigma: 0.1

gnss_local_online_sync: 1                       # if perform online synchronization betwen GNSS and local time
local_trigger_info_topic: "/external_trigger"   # external trigger info of the local sensor, if `gnss_local_online_sync` is 1
gnss_local_time_diff: 0.0                      # difference between GNSS and local time (s), if `gnss_local_online_sync` is 0

gnss_iono_default_parameters: !!opencv-matrix
   rows: 1
   cols: 8
   dt: d
   data: [0.1118E-07,  0.2235E-07, -0.4172E-06,  0.6557E-06,
          0.1249E+06, -0.4424E+06,  0.1507E+07, -0.2621E+06]


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.999491212860709, 0.031757149537694, 0.002966288500542, -0.006032399353045,
         -0.031850265593887, 0.998696634427672, 0.039882238708956, 0.002751451804162,
         -0.001695876123654, -0.039956424215385, 0.999199984071303,0.002757481683123,
         0., 0., 0., 1.]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.999490685673724, 0.031907628162628, 0.000522031134027, 0.089223961455974,
         -0.031903090706952, 0.998696816649207, 0.039835426671289, -0.000178031847180,
        0.000749703150183, -0.039831792324412, 0.999206118008397, 0.002246447738695,
         0., 0., 0., 1.]


#feature traker paprameters
max_cnt: 250            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
show_stereo: 1           # publish stereo image matching as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 1.6173701224327213e-01           # accelerometer measurement noise standard deviation. #2.5
gyr_n: 4.0215257386372735e-02           # gyroscope measurement noise standard deviation.     #0.05
acc_w: 3.5048022931587571e-04          # accelerometer bias random work noise standard deviation.  #3e-4
gyr_w: 2.3582424018057772e-05        # gyroscope bias random work noise standard deviation.     #1.6e-5
g_norm: 9.8         # gravity magnitude

# acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2   0.04
# gyr_n: 0.05         # gyroscope measurement noise standard deviation.     #0.05  0.004
# acc_w: 0.02         # accelerometer bias random work noise standard deviation.  #0.02
# gyr_w: 4.0e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
# g_norm: 9.792337 